export { BadgeVectorIcon, DEFAULT_BADGE_ICON_COLOR } from './BadgeVectorIcon'
export type { BadgeVectorIconProps } from './BadgeVectorIcon'
export { MotionBadgeIcon } from './MotionBadgeIcon'
export type { MotionBadgeIconProps } from './MotionBadgeIcon'
export { BADGE_VECTOR_BY_ID, BADGE_VECTOR_PATHS, BADGE_VECTOR_ALIGN } from './badgeVectorPaths'
export type { BadgeVectorName } from './badgeVectorPaths'
